# Generated by Django 3.0.3 on 2020-05-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsprofile',
            name='Experience',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
