# Generated by Django 3.0.3 on 2020-05-20 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0002_auto_20200520_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsprofile',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='EmProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='default.jpg', upload_to='profile_pics/')),
                ('CompanyName', models.CharField(max_length=100)),
                ('CompAddress', models.CharField(max_length=200)),
                ('IndType', models.CharField(max_length=100)),
                ('ContactPerson', models.CharField(max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
